sudo: false

language: c

os:
    - osx
    - linux

compiler:
    # we don't require a C compiler! if we don't specify one here, we get extra builds,
    # for both gcc and clang
    - gcc

env:
  global:
    - MOZ_BRANCH='mozilla-esr45'
    - DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
    - MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)

  matrix:
    # Test with our internal pypi mirror / en-US only
    - LOCALE='en-US'
      PIP_FIND_LINKS=http://pypi.pub.build.mozilla.org/pub
      PIP_NO_INDEX=1

    # ... and with the official pypi website
    - LOCALE='en-US'

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then /sbin/start-stop-daemon --start --quiet --make-pidfile --pidfile /tmp/custom_xvfb_99.pid --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x768x24 ; fi

install:
    - python .travis/create_venv.py ~/.venv
    - source ~/.venv/bin/activate

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --config ./.pep8.rc --exclude=client firefox_puppeteer/ firefox_ui_harness/ firefox_ui_tests/

    # Get the latest build and install it. Store the binary path in binary.txt
    - python .travis/download-and-install.py

script:
    # Run the tests with e10s disabled
    - cat binary.txt | xargs -I binary_path firefox-ui-functional --binary binary_path --gecko-log -

    # Run in e10s mode
    - cat binary.txt | xargs -I binary_path firefox-ui-functional --binary binary_path --gecko-log - --e10s

notifications:
    irc:
        - "irc.mozilla.org#automation"
