language: c

os:
    - osx
    - linux

compiler:
    # we don't require a C compiler! if we don't specify one here, we get extra builds,
    # for both gcc and clang
    - gcc

env:
    - DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
      MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)

before_install:
    - ./.travis/before_install.sh

    - virtualenv ~/.venv
    - source ~/.venv/bin/activate

install:
    # We need to either pin our marionette version or get every dependent package from
    # tree to avoid bustage. Pinning marionette means we're more likely to work out of the
    # the box for those working locally without a clone of m-c.
    # - svn checkout https://github.com/mozilla/gecko-dev/trunk/testing/marionette/client
    # - "cd client && python setup.py develop && cd .."

    - python setup.py develop
    - pip install mozdownload mozinstall pep8

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --max-line-length=99 --exclude=client .

    # Download latest Firefox Nightly, which is compatible with the Marionette client version used
    - mozdownload -t daily

script:
    # Run in non-e10s mode
    - firefox-ui-tests --installer *-firefox-*

    # Run in e10s mode
    - firefox-ui-tests --installer *-firefox-* --e10s

notifications:
    email:
        - dev-automation@lists.mozilla.org
    irc:
        - "irc.mozilla.org#automation"
