language: c

branches:
  exclude:
    # Do not run tests for ESR releases, because there are no latest builds available
    - /^mozilla-esr.*$/

os:
    - osx
    - linux

compiler:
    # we don't require a C compiler! if we don't specify one here, we get extra builds,
    # for both gcc and clang
    - gcc

env:
    # Test with our internal pypi mirror
    - PIP_FIND_LINKS=http://pypi.pub.build.mozilla.org/pub
      PIP_NO_INDEX=1
      DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
      MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)
    # ... and with the official pypi website
    - DISPLAY=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo ':99'; fi)
      MOZ_XVFB=$(if [[ $TRAVIS_OS_NAME = 'linux' ]]; then echo 1; fi)

before_install:
    - ./.travis/before_install.sh

install:
    # We need to either pin our marionette version or get every dependent package from
    # tree to avoid bustage. Pinning marionette means we're more likely to work out of the
    # the box for those working locally without a clone of m-c.
    # - svn checkout https://github.com/mozilla/gecko-dev/trunk/testing/marionette/client
    # - "cd client && python setup.py develop && cd .."

    - python create_venv.py --with-optional-packages ~/.venv
    - source ~/.venv/bin/activate

before_script:
    # Run pep8 on all except the checked out marionette-client folder
    - pep8 --config ./.pep8.rc --exclude=client .

    # Prepare the build and everything else
    - ./.travis/before_script.sh

script:
    # Run in non-e10s mode
    - firefox-ui-tests --installer *firefox-* --gecko-log -

    # Run in e10s mode
    - firefox-ui-tests --installer *firefox-* --gecko-log - --e10s

notifications:
    irc:
        - "irc.mozilla.org#automation"
