language: python

python:
    - 2.7

env: DISPLAY=:99

before_install:
    - sudo apt-get update
    - "/sbin/start-stop-daemon --start --quiet --make-pidfile --pidfile /tmp/custom_xvfb_99.pid --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1024x768x24"

install:
    - sudo apt-get install flashplugin-nonfree subversion

    # As long as we have invasive changes lets get the trunk version of marionette-client
    - svn checkout https://github.com/mozilla/gecko-dev/trunk/testing/marionette/client
    - "cd client && python setup.py develop && cd .."

    - python setup.py develop
    - pip install mozdownload pep8

before_script:
    - pep8 --max-line-length=99 firefoxtests

    # Download Firefox Nightly which is compatible with the used version of
    # marionette client
    - mozdownload -t daily
    - tar -xvf *firefox*.tar.bz2

script:
    - firefox-ui-tests --binary firefox/firefox

notifications:
#      email:
#          - dev-automation@lists.mozilla.org
    irc:
        - "irc.mozilla.org#automation"